apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegis-platform.fullname" . }}
  labels:
    {{- include "aegis-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 8000 }}
      protocol: TCP
      name: http
  selector:
    {{- include "aegis-platform.selectorLabels" . | nindent 4 }}
